### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by adhislims** [nandangsetianugraha/APINS-2023.a#1]
kenapa ya tulisannya Halaman Ini Saat Ini Tidak Tersedia
Ini bisa dikarenakan kesalahan teknis yang sedang kami perbaiki.
Coba muat ulang halaman ini. setelah login

**Comment by nandangsetianugraha** [comment]
pada index.php sesuaikan params nya
misalkan web nya berada di directory http://localhost/apins
maka 
$halaman = $params[3];
$tipe = count($params)>4 ? $params[4] : '';
$act = count($params)>5 ? $params[5] : '';
diubah menjadi 
$halaman = $params[2];
$tipe = count($params)>3 ? $params[3] : '';
$act = count($params)>4 ? $params[4] : '';
